set_property -dict {PACKAGE_PIN T22 IOSTANDARD LVCMOS33} [get_ports UART_0_rxd]
set_property -dict {PACKAGE_PIN T21 IOSTANDARD LVCMOS33} [get_ports UART_0_txd]

#FPGA LED
set_property -dict {PACKAGE_PIN N19 IOSTANDARD LVCMOS33} [get_ports {gpio_rtl_tri_o[0]}]
set_property -dict {PACKAGE_PIN N17 IOSTANDARD LVCMOS33} [get_ports {gpio_rtl_tri_o[1]}]
set_property -dict {PACKAGE_PIN P16 IOSTANDARD LVCMOS33} [get_ports {gpio_rtl_tri_o[2]}]
set_property -dict {PACKAGE_PIN N15 IOSTANDARD LVCMOS33} [get_ports {gpio_rtl_tri_o[3]}]
set_property -dict {PACKAGE_PIN V18 IOSTANDARD LVCMOS33} [get_ports {gpio_rtl_tri_o[4]}]
set_property -dict {PACKAGE_PIN W17 IOSTANDARD LVCMOS33} [get_ports {gpio_rtl_tri_o[5]}]
set_property -dict {PACKAGE_PIN AA21 IOSTANDARD LVCMOS33} [get_ports {gpio_rtl_tri_o[6]}]
set_property -dict {PACKAGE_PIN AB19 IOSTANDARD LVCMOS33} [get_ports {gpio_rtl_tri_o[7]}]

#DAC
set_property -dict {PACKAGE_PIN F22 IOSTANDARD LVCMOS33} [get_ports DAC_Mode]
set_property -dict {PACKAGE_PIN C22 IOSTANDARD LVCMOS33} [get_ports DAC_Sleep]
set_property -dict {PACKAGE_PIN B19 IOSTANDARD LVCMOS33} [get_ports DAC_Clk]
set_property -dict {PACKAGE_PIN B20 IOSTANDARD LVCMOS33} [get_ports {DAC_Data[13]}]
set_property -dict {PACKAGE_PIN A19 IOSTANDARD LVCMOS33} [get_ports {DAC_Data[12]}]
set_property -dict {PACKAGE_PIN A17 IOSTANDARD LVCMOS33} [get_ports {DAC_Data[11]}]
set_property -dict {PACKAGE_PIN B15 IOSTANDARD LVCMOS33} [get_ports {DAC_Data[10]}]
set_property -dict {PACKAGE_PIN D17 IOSTANDARD LVCMOS33} [get_ports {DAC_Data[9]}]
set_property -dict {PACKAGE_PIN D21 IOSTANDARD LVCMOS33} [get_ports {DAC_Data[8]}]
set_property -dict {PACKAGE_PIN F17 IOSTANDARD LVCMOS33} [get_ports {DAC_Data[7]}]
set_property -dict {PACKAGE_PIN P18 IOSTANDARD LVCMOS33} [get_ports {DAC_Data[6]}]
set_property -dict {PACKAGE_PIN K18 IOSTANDARD LVCMOS33} [get_ports {DAC_Data[5]}]
set_property -dict {PACKAGE_PIN M17 IOSTANDARD LVCMOS33} [get_ports {DAC_Data[4]}]
set_property -dict {PACKAGE_PIN U16 IOSTANDARD LVCMOS33} [get_ports {DAC_Data[3]}]
set_property -dict {PACKAGE_PIN V15 IOSTANDARD LVCMOS33} [get_ports {DAC_Data[2]}]
set_property -dict {PACKAGE_PIN U9  IOSTANDARD LVCMOS33} [get_ports {DAC_Data[1]}]
set_property -dict {PACKAGE_PIN U5  IOSTANDARD LVCMOS33} [get_ports {DAC_Data[0]}]

#ADC
#set_property -dict {PACKAGE_PIN M19 IOSTANDARD LVCMOS33} [get_ports ADC_PowerDown]
#set_property -dict {PACKAGE_PIN M21 IOSTANDARD LVCMOS33} [get_ports ADC_OverRange]
#set_property -dict {PACKAGE_PIN M22 IOSTANDARD LVCMOS33} [get_ports {ADC_Data[9]}]
#set_property -dict {PACKAGE_PIN N20 IOSTANDARD LVCMOS33} [get_ports {ADC_Data[8]}]
#set_property -dict {PACKAGE_PIN N18 IOSTANDARD LVCMOS33} [get_ports {ADC_Data[7]}]
#set_property -dict {PACKAGE_PIN R16 IOSTANDARD LVCMOS33} [get_ports {ADC_Data[6]}]
#set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS33} [get_ports {ADC_Data[5]}]
#set_property -dict {PACKAGE_PIN V19 IOSTANDARD LVCMOS33} [get_ports {ADC_Data[4]}]
#set_property -dict {PACKAGE_PIN W18 IOSTANDARD LVCMOS33} [get_ports {ADC_Data[3]}]
#set_property -dict {PACKAGE_PIN AB21 IOSTANDARD LVCMOS33} [get_ports {ADC_Data[2]}]
#set_property -dict {PACKAGE_PIN AB20 IOSTANDARD LVCMOS33} [get_ports {ADC_Data[1]}]
#set_property -dict {PACKAGE_PIN AA19 IOSTANDARD LVCMOS33} [get_ports {ADC_Data[0]}]
#set_property -dict {PACKAGE_PIN AA18 IOSTANDARD LVCMOS33} [get_ports ADC_Clk]