# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/DIY/Radio_SW/VivadoProjectFolder/myproject/myproject.srcs/sources_1/bd/TopBlockDesign/ip/TopBlockDesign_auto_pc_0/TopBlockDesign_auto_pc_0.xci
# IP: The module: 'TopBlockDesign_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/DIY/Radio_SW/VivadoProjectFolder/myproject/myproject.srcs/sources_1/bd/TopBlockDesign/ip/TopBlockDesign_auto_pc_0/TopBlockDesign_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TopBlockDesign_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/DIY/Radio_SW/VivadoProjectFolder/myproject/myproject.srcs/sources_1/bd/TopBlockDesign/ip/TopBlockDesign_auto_pc_0/TopBlockDesign_auto_pc_0.xci
# IP: The module: 'TopBlockDesign_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/DIY/Radio_SW/VivadoProjectFolder/myproject/myproject.srcs/sources_1/bd/TopBlockDesign/ip/TopBlockDesign_auto_pc_0/TopBlockDesign_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TopBlockDesign_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
