# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/DIY/Radio_SW/Constrains/Constrains.xdc

# Block Designs: bd/TopBlockDesign/TopBlockDesign.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TopBlockDesign || ORIG_REF_NAME==TopBlockDesign} -quiet] -quiet

# IP: bd/TopBlockDesign/ip/TopBlockDesign_DAC_Control_0_0/TopBlockDesign_DAC_Control_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TopBlockDesign_DAC_Control_0_0 || ORIG_REF_NAME==TopBlockDesign_DAC_Control_0_0} -quiet] -quiet

# IP: bd/TopBlockDesign/ip/TopBlockDesign_DDS_0_0/TopBlockDesign_DDS_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TopBlockDesign_DDS_0_0 || ORIG_REF_NAME==TopBlockDesign_DDS_0_0} -quiet] -quiet

# IP: bd/TopBlockDesign/ip/TopBlockDesign_DDS_Control_0_0/TopBlockDesign_DDS_Control_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TopBlockDesign_DDS_Control_0_0 || ORIG_REF_NAME==TopBlockDesign_DDS_Control_0_0} -quiet] -quiet

# IP: bd/TopBlockDesign/ip/TopBlockDesign_axi_gpio_0_0/TopBlockDesign_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TopBlockDesign_axi_gpio_0_0 || ORIG_REF_NAME==TopBlockDesign_axi_gpio_0_0} -quiet] -quiet

# IP: bd/TopBlockDesign/ip/TopBlockDesign_xbar_0/TopBlockDesign_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TopBlockDesign_xbar_0 || ORIG_REF_NAME==TopBlockDesign_xbar_0} -quiet] -quiet

# IP: bd/TopBlockDesign/ip/TopBlockDesign_auto_pc_0/TopBlockDesign_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TopBlockDesign_auto_pc_0 || ORIG_REF_NAME==TopBlockDesign_auto_pc_0} -quiet] -quiet

# IP: bd/TopBlockDesign/ip/TopBlockDesign_axi_interconnect_0_0/TopBlockDesign_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TopBlockDesign_axi_interconnect_0_0 || ORIG_REF_NAME==TopBlockDesign_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/TopBlockDesign/ip/TopBlockDesign_clk_wiz_0_0/TopBlockDesign_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TopBlockDesign_clk_wiz_0_0 || ORIG_REF_NAME==TopBlockDesign_clk_wiz_0_0} -quiet] -quiet

# IP: bd/TopBlockDesign/ip/TopBlockDesign_proc_sys_reset_0_0/TopBlockDesign_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TopBlockDesign_proc_sys_reset_0_0 || ORIG_REF_NAME==TopBlockDesign_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/TopBlockDesign/ip/TopBlockDesign_processing_system7_0_0/TopBlockDesign_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TopBlockDesign_processing_system7_0_0 || ORIG_REF_NAME==TopBlockDesign_processing_system7_0_0} -quiet] -quiet

# IP: bd/TopBlockDesign/ip/TopBlockDesign_xlslice_0_0/TopBlockDesign_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TopBlockDesign_xlslice_0_0 || ORIG_REF_NAME==TopBlockDesign_xlslice_0_0} -quiet] -quiet

# XDC: bd/TopBlockDesign/TopBlockDesign_ooc.xdc
