# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/DIY/Radio_SW/VivadoProjectFolder/myproject/myproject.srcs/sources_1/bd/TopBlockDesign/ip/TopBlockDesign_processing_system7_0_0/TopBlockDesign_processing_system7_0_0.xci
# IP: The module: 'TopBlockDesign_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/DIY/Radio_SW/VivadoProjectFolder/myproject/myproject.srcs/sources_1/bd/TopBlockDesign/ip/TopBlockDesign_processing_system7_0_0/TopBlockDesign_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'TopBlockDesign_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/DIY/Radio_SW/VivadoProjectFolder/myproject/myproject.srcs/sources_1/bd/TopBlockDesign/ip/TopBlockDesign_processing_system7_0_0/TopBlockDesign_processing_system7_0_0.xci
# IP: The module: 'TopBlockDesign_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/DIY/Radio_SW/VivadoProjectFolder/myproject/myproject.srcs/sources_1/bd/TopBlockDesign/ip/TopBlockDesign_processing_system7_0_0/TopBlockDesign_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'TopBlockDesign_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
